export const ROUTES = {
  login: "/login",
  root: "/",
  dashboard: "/dashboard",
  fleet: "/fleet",
  aircraftRecord: (tail: string) => `/fleet/${tail}`,
  inspections: "/inspections",
  components: "/components",
  findings: "/findings",
  compliance: "/compliance",
  lifeTracking: "/life-tracking",
  reports: "/reports",
  partsRequests: "/parts-requests",
  maintenanceHistory: "/maintenance-history",
  documents: "/documents",
  technicalLibrary: "/technical-library",
  knowledgeBase: "/knowledge-base",
  clientAccess: "/client-access",
  clientReports: "/client-reports",
  presentations: "/presentations",
  aiAssistant: "/ai-assistant",
  inspectionPresentation: (id?: string) => `/inspection-presentation${id ? `/${id}` : ""}`,
  damage3d: "/damage-3d",
  qaQc: "/qa-qc",
  delivery: "/delivery",
  usersRoles: "/users-roles",
  templates: "/templates",
  auditLog: "/audit-log",
  systemSettings: "/system-settings",
  view: (slug: string) => `/view/${slug}`,
} as const;

export function slugify(label: string): string {
  return label.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}
