import { useState } from "react";
import { History } from "lucide-react";
import { demoAuditEvents, type DemoAuditEvent } from "@/data/mock/audit-log";
import { FilterableTable } from "@/components/shared/FilterableTable";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { AdminCount, AdminHeading } from "./AdminShared";

const label = (value: string) => value.replaceAll("_", " ").replaceAll(".", " · ");
const stamp = (value: string) => new Date(value).toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" });
export function AuditLogPage() {
  const [query, setQuery] = useState("");
  const [actor, setActor] = useState("all");
  const [action, setAction] = useState("all");
  const [entity, setEntity] = useState("all");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [selected, setSelected] = useState<DemoAuditEvent | null>(null);
  const [limit, setLimit] = useState(20);
  const visible = demoAuditEvents.filter(event => `${event.actor} ${event.action} ${event.entityType} ${event.entityId}`.toLowerCase().includes(query.toLowerCase()) && (actor === "all" || event.actor === actor) && (action === "all" || event.action === action) && (entity === "all" || event.entityType === entity) && (!from || event.timestamp.slice(0, 10) >= from) && (!to || event.timestamp.slice(0, 10) <= to));
  const keys = selected ? Array.from(new Set([...Object.keys(selected.beforeState ?? {}), ...Object.keys(selected.afterState ?? {})])) : [];
  return <section className="admin-page"><AdminHeading title="Audit Log" description="Inspect activity across maintenance, quality and delivery records." />
    <div className="admin-counts"><AdminCount value={demoAuditEvents.length} label="Events" detail="sample activity" /><AdminCount value={new Set(demoAuditEvents.map(event => event.actor)).size} label="Actors" detail="in this sample" /><AdminCount value={new Set(demoAuditEvents.map(event => event.entityType)).size} label="Record types" detail="tracked here" /></div>
    <div className="panel admin-table"><div className="admin-section-title"><div><History size={18} /><h2>Activity timeline</h2></div><span>{visible.length} events</span></div><p className="admin-inline-note">Illustrative audit entries. The application writes real audit events, but this viewer is awaiting a read endpoint.</p><FilterableTable rows={visible.slice(0, limit)} getRowId={event => event.id} searchValue={query} onSearchChange={setQuery} searchPlaceholder="Search activity…" filters={<div className="admin-audit-filters"><select aria-label="Filter by actor" value={actor} onChange={event => setActor(event.target.value)}><option value="all">All actors</option>{Array.from(new Set(demoAuditEvents.map(event => event.actor))).map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filter by action" value={action} onChange={event => setAction(event.target.value)}><option value="all">All actions</option>{Array.from(new Set(demoAuditEvents.map(event => event.action))).map(value => <option key={value} value={value}>{label(value)}</option>)}</select><select aria-label="Filter by entity type" value={entity} onChange={event => setEntity(event.target.value)}><option value="all">All record types</option>{Array.from(new Set(demoAuditEvents.map(event => event.entityType))).map(value => <option key={value} value={value}>{label(value)}</option>)}</select><label>From<input aria-label="From date" type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label>To<input aria-label="To date" type="date" value={to} onChange={event => setTo(event.target.value)} /></label></div>} columns={[{ key: "time", header: "Timestamp", render: event => stamp(event.timestamp) }, { key: "actor", header: "Actor", render: event => <strong className="admin-primary-cell">{event.actor}</strong> }, { key: "action", header: "Action", render: event => <span className="admin-role">{label(event.action)}</span> }, { key: "entity", header: "Record", render: event => `${label(event.entityType)} · ${event.entityId}` }, { key: "detail", header: "", render: event => <button className="admin-link" onClick={() => setSelected(event)}>View change</button> }]} footer={<div className="admin-table-footer"><span>Showing {Math.min(limit, visible.length)} of {visible.length} matching events</span>{visible.length > limit && <button className="secondary-button" onClick={() => setLimit(current => current + 20)}>Load more</button>}</div>} /></div>
    <Dialog open={!!selected} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent className="admin-dialog"><DialogTitle>Change details</DialogTitle><DialogDescription>{selected?.id} · {selected && stamp(selected.timestamp)}</DialogDescription><div className="admin-detail-grid"><span>Actor</span><strong>{selected?.actor}</strong><span>Action</span><strong>{selected && label(selected.action)}</strong><span>Record</span><strong>{selected?.entityType} / {selected?.entityId}</strong></div><h3>Before / after</h3><div className="admin-diff"><div><h4>Before</h4>{keys.map(key => <p key={key}><span>{label(key)}</span><strong>{selected?.beforeState?.[key] ?? "—"}</strong></p>)}</div><div><h4>After</h4>{keys.map(key => <p key={key}><span>{label(key)}</span><strong>{selected?.afterState?.[key] ?? "—"}</strong></p>)}</div></div><p className="admin-session-copy">This is an illustrative event, not a live audit record.</p></DialogContent></Dialog>
  </section>;
}
