import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Download, History, Shield } from "lucide-react";
import { useAuth } from "@/lib/auth";
import { FilterableTable } from "@/components/shared/FilterableTable";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";

type AuditEvent = { id: string; actor: string; action: string; entityType: string; entityId: string; beforeState: Record<string, unknown> | null; afterState: Record<string, unknown> | null; timestamp: string };
type AuditResponse = { events: AuditEvent[]; page: number; pageSize: number; total: number };
type Filters = { actor: string; action: string; entityType: string; from: string; to: string };
const emptyFilters: Filters = { actor: "", action: "", entityType: "", from: "", to: "" };
const label = (value: string) => value.replaceAll("_", " ").replaceAll(".", " · ");
const stamp = (value: string) => new Date(value).toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" });
async function json<T>(response: Response): Promise<T> { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? `Request failed (${response.status})`); return body as T; }
function fetchEvents(filters: Filters, page: number, pageSize: number) { const params = new URLSearchParams({ page: String(page), pageSize: String(pageSize) }); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, key === "to" ? `${value}T23:59:59.999Z` : key === "from" ? `${value}T00:00:00.000Z` : value); }); return fetch(`/api/audit-events?${params}`).then(json<AuditResponse>); }
const fetchEntityTypes = () => fetch("/api/audit-events/entity-types").then(json<string[]>);
function valueText(value: unknown): string { return value === null || value === undefined ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value); }
function exportCsv(events: AuditEvent[]) { const cells = [["Timestamp", "Actor", "Action", "Entity type", "Entity ID", "Before", "After"], ...events.map(event => [event.timestamp, event.actor, event.action, event.entityType, event.entityId, valueText(event.beforeState), valueText(event.afterState)])]; const csv = cells.map(row => row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob(["\uFEFF", csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `audit-events-${new Date().toISOString().slice(0, 10)}.csv`; document.body.append(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
export function AuditLogPage() {
  const { user } = useAuth();
  const allowed = user?.role === "Admin" || user?.role === "QA";
  const [draft, setDraft] = useState<Filters>(emptyFilters);
  const [filters, setFilters] = useState<Filters>(emptyFilters);
  const [data, setData] = useState<AuditResponse>({ events: [], page: 1, pageSize: 20, total: 0 });
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [entityTypes, setEntityTypes] = useState<string[]>([]);
  const [selected, setSelected] = useState<AuditEvent | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { if (!allowed) return; fetchEntityTypes().then(setEntityTypes).catch(err => setError(err.message)); }, [allowed]);
  useEffect(() => { if (!allowed) return; let active = true; setLoading(true); fetchEvents(filters, page, pageSize).then(result => { if (active) { setData(result); setError(""); } }).catch(err => { if (active) setError(err.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [allowed, filters, page, pageSize]);
  if (user && !allowed) return <section className="admin-page"><div className="panel admin-access-denied"><Shield size={26} /><h1>Access denied</h1><p>Audit Log is available to Admin and QA users.</p></div></section>;
  const update = (key: keyof Filters, value: string) => setDraft(current => ({ ...current, [key]: value }));
  const keys = selected ? Array.from(new Set([...Object.keys(selected.beforeState ?? {}), ...Object.keys(selected.afterState ?? {})])) : [];
  const pageCount = Math.max(1, Math.ceil(data.total / data.pageSize));
  return <section className="admin-page admin-live-page"><header className="page-heading admin-heading"><div><div className="eyebrow"><Shield size={13} /> ADMIN / WORKSPACE</div><h1>Audit Log</h1><p>Inspect recorded activity across the workspace.</p></div><button className="secondary-button" disabled={!data.events.length} onClick={() => exportCsv(data.events)}><Download size={14} /> Export this page</button></header>
    <div className="panel admin-table"><div className="admin-section-title"><div><History size={18} /><h2>Activity timeline</h2></div><span>{data.total} events</span></div>
      <form className="admin-live-filters" onSubmit={event => { event.preventDefault(); setPage(1); setFilters({ ...draft }); }}><label>Actor<input aria-label="Actor" value={draft.actor} onChange={event => update("actor", event.target.value)} placeholder="Search actor" /></label><label>Action<input aria-label="Action" value={draft.action} onChange={event => update("action", event.target.value)} placeholder="Search action" /></label><label>Record type<select aria-label="Record type" value={draft.entityType} onChange={event => update("entityType", event.target.value)}><option value="">All types</option>{entityTypes.map(type => <option key={type} value={type}>{label(type)}</option>)}</select></label><label>From<input aria-label="From date" type="date" value={draft.from} max={draft.to || undefined} onChange={event => update("from", event.target.value)} /></label><label>To<input aria-label="To date" type="date" value={draft.to} min={draft.from || undefined} onChange={event => update("to", event.target.value)} /></label><button className="primary-button" type="submit">Apply</button><button className="secondary-button" type="button" onClick={() => { setDraft(emptyFilters); setFilters(emptyFilters); setPage(1); }}>Reset</button></form>
      {error && <p className="admin-api-error" role="alert">{error}</p>}
      <FilterableTable rows={data.events} getRowId={event => event.id} emptyMessage={loading ? "Loading audit events…" : "No audit events match these filters."} columns={[{ key: "time", header: "Timestamp", render: event => stamp(event.timestamp) }, { key: "actor", header: "Actor", render: event => <strong className="admin-primary-cell">{event.actor}</strong> }, { key: "action", header: "Action", render: event => <span className="admin-role">{label(event.action)}</span> }, { key: "entity", header: "Record", render: event => `${label(event.entityType)} · ${event.entityId}` }, { key: "detail", header: "", render: event => <button className="admin-link" onClick={() => setSelected(event)}>View change</button> }]} footer={<div className="admin-table-footer"><span>Showing {data.total ? (data.page - 1) * data.pageSize + 1 : 0}–{Math.min(data.page * data.pageSize, data.total)} of {data.total}</span><div className="admin-pagination"><button aria-label="Previous page" disabled={page <= 1 || loading} onClick={() => setPage(current => current - 1)}><ChevronLeft size={15} /></button><span>Page {data.page} of {pageCount}</span><button aria-label="Next page" disabled={page >= pageCount || loading} onClick={() => setPage(current => current + 1)}><ChevronRight size={15} /></button><label>Rows <select aria-label="Rows per page" value={pageSize} onChange={event => { setPageSize(Number(event.target.value)); setPage(1); }}><option>20</option><option>50</option><option>100</option></select></label></div></div>} />
    </div>
    <Dialog open={!!selected} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent className="admin-dialog"><DialogTitle>Change details</DialogTitle><DialogDescription>{selected?.id} · {selected && stamp(selected.timestamp)}</DialogDescription><div className="admin-detail-grid"><span>Actor</span><strong>{selected?.actor}</strong><span>Action</span><strong>{selected && label(selected.action)}</strong><span>Record</span><strong>{selected?.entityType} / {selected?.entityId}</strong></div><h3>Before / after</h3>{keys.length ? <div className="admin-diff"><div><h4>Before</h4>{keys.map(key => <p key={key}><span>{label(key)}</span><strong>{valueText(selected?.beforeState?.[key])}</strong></p>)}</div><div><h4>After</h4>{keys.map(key => <p key={key}><span>{label(key)}</span><strong>{valueText(selected?.afterState?.[key])}</strong></p>)}</div></div> : <p className="admin-setting-help">No state snapshot was recorded for this event.</p>}</DialogContent></Dialog>
  </section>;
}
