import { useState } from "react";
import { Bell, Building2, Gauge, Save, Settings } from "lucide-react";
import { toast } from "sonner";
import { AdminHeading } from "./AdminShared";

const initial = { company: "WingBox Aviation", email: "operations@wingbox.aero", phone: "+63 2 8840 2200", timezone: "Asia/Manila", threshold: "10", dueSoon: true, qc: true, delivery: false, digest: true };
export function SystemSettingsPage() {
  const [settings, setSettings] = useState(initial);
  const update = <K extends keyof typeof initial>(key: K, value: typeof initial[K]) => setSettings(current => ({ ...current, [key]: value }));
  return <section className="admin-page"><AdminHeading title="System Settings" description="Review fleet-wide defaults, organization details and notification preferences." />
    <div className="admin-settings-grid"><div className="panel admin-setting-card"><div className="admin-setting-head"><Building2 size={18} /><div><h2>Organization</h2><p>Details shown on internal records and report previews.</p></div></div><div className="admin-form-grid"><label>Company name<input value={settings.company} onChange={event => update("company", event.target.value)} /></label><label>Contact email<input type="email" value={settings.email} onChange={event => update("email", event.target.value)} /></label><label>Contact phone<input value={settings.phone} onChange={event => update("phone", event.target.value)} /></label><label>Time zone<select value={settings.timezone} onChange={event => update("timezone", event.target.value)}><option value="Asia/Manila">Asia/Manila (PHT)</option><option value="UTC">UTC</option><option value="Asia/Singapore">Asia/Singapore (SGT)</option></select></label></div></div>
      <div className="panel admin-setting-card"><div className="admin-setting-head"><Bell size={18} /><div><h2>Notifications</h2><p>Choose the events this workspace would surface.</p></div></div><div className="admin-toggle-list">{([{ key: "dueSoon", name: "Life limit warnings", detail: "Alert when components approach a tracked limit." }, { key: "qc", name: "Quality sign-offs", detail: "Notify on completed QA/QC checklists." }, { key: "delivery", name: "Delivery milestones", detail: "Show aircraft handover status changes." }, { key: "digest", name: "Weekly fleet digest", detail: "Summarize open items once a week." }] as const).map(item => <label key={item.key}><span><strong>{item.name}</strong><small>{item.detail}</small></span><input type="checkbox" checked={settings[item.key]} onChange={event => update(item.key, event.target.checked)} /></label>)}</div></div>
      <div className="panel admin-setting-card admin-threshold-card"><div className="admin-setting-head"><Gauge size={18} /><div><h2>Life tracking</h2><p>Set the warning window for limits approaching expiry.</p></div></div><div className="admin-threshold-field"><label>Warn when remaining life is at or below<input type="number" min="1" max="100" value={settings.threshold} onChange={event => update("threshold", event.target.value)} /></label><span>%</span></div><p className="admin-setting-help">Current backend rule is fixed at 10%. This field previews a possible configuration and does not change live warnings.</p></div>
      <div className="panel admin-setting-card admin-save-card"><Settings size={22} /><h2>Local preview</h2><p>You can explore settings in this session. Reloading restores the demo defaults.</p><button className="primary-button" onClick={() => toast.info("Settings are not saved.", { description: "Backend settings support is not connected; this is a session-only preview." })}><Save size={15} /> Save Changes</button></div></div>
  </section>;
}
