import { DemoDataBadge } from "@/components/DemoDataBadge";
import { useEffect, useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ClipboardCheck, Plus, Shield } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { FilterableTable } from "@/components/shared/FilterableTable";
import { StatusPill } from "@/components/shared/StatusPill";

type ApiAction = { id: string; clientId: string | null; subjectType: string; subjectId: string; title: string; description: string | null; ownerId: string | null; dueDate: string | null; status: string; sourceType: string | null; sourceId: string | null; closedBy: string | null; closedAt: string | null; closureNote: string | null; createdAt: string };
const schema = z.object({ subjectType: z.string().trim().min(1, "Subject type is required"), subjectId: z.string().trim().min(1, "Subject ID is required"), title: z.string().trim().min(1, "Title is required"), description: z.string().optional(), ownerId: z.union([z.literal(""), z.uuid("Enter a valid owner UUID")]).optional(), dueDate: z.string().optional(), sourceType: z.string().optional(), sourceId: z.string().optional() });
type Values = z.infer<typeof schema>;
const defaults: Values = { subjectType: "", subjectId: "", title: "", description: "", ownerId: "", dueDate: "", sourceType: "", sourceId: "" };
async function json<T>(response: Response): Promise<T> { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? `Request failed (${response.status})`); return body as T; }
const fetchActions = (status: string) => fetch(`/api/actions${status ? `?status=${encodeURIComponent(status)}` : ""}`).then(json<ApiAction[]>);
const createAction = (values: Values) => fetch("/api/actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(Object.entries(values).filter(([, value]) => value))) }).then(json<ApiAction>);
const closeAction = (id: string, closureNote: string) => fetch(`/api/actions/${encodeURIComponent(id)}/close`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ closureNote }) }).then(json<ApiAction>);
export function ActionsPage() {
  const [rows, setRows] = useState<ApiAction[]>([]);
  const [status, setStatus] = useState("open");
  const [open, setOpen] = useState(false);
  const [closing, setClosing] = useState<ApiAction | null>(null);
  const [note, setNote] = useState("");
  const [savingClose, setSavingClose] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: defaults });
  useEffect(() => { let active = true; setLoading(true); fetchActions(status).then(data => { if (active) { setRows(data); setError(""); } }).catch(err => { if (active) setError(err.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [status]);
  const create = async (values: Values) => { try { const created = await createAction(values); if (!status || status === created.status) setRows(current => [created, ...current]); toast.success("Action created."); reset(defaults); setOpen(false); } catch (err) { toast.error(err instanceof Error ? err.message : "Unable to create action."); } };
  const close = async () => { if (!closing || !note.trim()) return; setSavingClose(true); try { const updated = await closeAction(closing.id, note.trim()); setRows(current => status === "open" ? current.filter(row => row.id !== updated.id) : current.map(row => row.id === updated.id ? updated : row)); toast.success("Action closed."); setClosing(null); setNote(""); } catch (err) { toast.error(err instanceof Error ? err.message : "Unable to close action."); } finally { setSavingClose(false); } };
  return <section className="admin-page admin-live-page"><DemoDataBadge variant="page" note="Seeded demo client records." /><header className="page-heading admin-heading"><div><div className="eyebrow"><Shield size={13} /> WORKSPACE / TRACKING</div><h1>Actions</h1><p>Assign work, track due dates and record closure.</p></div><button className="primary-button" onClick={() => setOpen(true)}><Plus size={15} /> New Action</button></header><div className="panel admin-table"><div className="admin-section-title"><div><ClipboardCheck size={18} /><h2>Action register</h2></div><span>{rows.length} {status || "total"}</span></div><div className="admin-tabs" role="tablist" aria-label="Action status">{[["open", "Open"], ["closed", "Closed"], ["", "All"]].map(([value, label]) => <button key={label} role="tab" aria-selected={status === value} className={status === value ? "active" : ""} onClick={() => setStatus(value)}>{label}</button>)}</div>{error && <p className="admin-api-error" role="alert">{error}</p>}<FilterableTable rows={rows} getRowId={row => row.id} emptyMessage={loading ? "Loading actions…" : status === "open" ? "No open actions. Create one to start tracking work." : "No actions in this view."} columns={[{ key: "title", header: "Action", render: row => <div className="admin-action-title"><strong className="admin-primary-cell">{row.title}</strong><small>{row.description || row.id}</small></div> }, { key: "subject", header: "Subject", render: row => `${row.subjectType} · ${row.subjectId}` }, { key: "owner", header: "Owner", render: row => row.ownerId ?? "Unassigned" }, { key: "due", header: "Due", render: row => row.dueDate ? new Date(`${row.dueDate}T12:00:00Z`).toLocaleDateString() : "—" }, { key: "status", header: "Status", render: row => <StatusPill status={row.status} /> }, { key: "close", header: "", render: row => row.status === "open" ? <button className="admin-link" onClick={() => { setClosing(row); setNote(""); }}>Close</button> : <span title={row.closureNote ?? ""}>Closed {row.closedAt ? new Date(row.closedAt).toLocaleDateString() : ""}</span> }]} /></div>
    <Dialog open={open} onOpenChange={next => { setOpen(next); if (!next) reset(defaults); }}><DialogContent className="admin-dialog admin-action-dialog"><DialogTitle>New Action</DialogTitle><DialogDescription>Create a tracked action for a record or subject.</DialogDescription><form onSubmit={handleSubmit(create)} className="admin-live-form"><label>Title<input {...register("title")} placeholder="What needs to be done?" />{errors.title && <small className="admin-form-error">{errors.title.message}</small>}</label><div className="admin-form-grid"><label>Subject type<input {...register("subjectType")} placeholder="e.g. aircraft, component" />{errors.subjectType && <small className="admin-form-error">{errors.subjectType.message}</small>}</label><label>Subject ID<input {...register("subjectId")} placeholder="Record ID" />{errors.subjectId && <small className="admin-form-error">{errors.subjectId.message}</small>}</label></div><label>Description<textarea rows={3} {...register("description")} /></label><div className="admin-form-grid"><label>Owner ID (optional)<input {...register("ownerId")} placeholder="User UUID" />{errors.ownerId && <small className="admin-form-error">{errors.ownerId.message}</small>}</label><label>Due date<input type="date" {...register("dueDate")} /></label></div><div className="admin-form-grid"><label>Source type (optional)<input {...register("sourceType")} /></label><label>Source ID (optional)<input {...register("sourceId")} /></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancel</button><button type="submit" className="primary-button" disabled={isSubmitting}>{isSubmitting ? "Creating…" : "Create Action"}</button></div></form></DialogContent></Dialog>
    <Dialog open={!!closing} onOpenChange={next => { if (!next) setClosing(null); }}><DialogContent className="admin-dialog"><DialogTitle>Close action</DialogTitle><DialogDescription>{closing?.title}</DialogDescription><div className="admin-live-form"><label>Closure note<textarea rows={4} value={note} onChange={event => setNote(event.target.value)} placeholder="Describe what was completed…" /></label><div className="modal-actions"><button className="secondary-button" onClick={() => setClosing(null)}>Cancel</button><button className="primary-button" disabled={!note.trim() || savingClose} onClick={close}>{savingClose ? "Closing…" : "Close Action"}</button></div></div></DialogContent></Dialog>
  </section>;
}
