import { useEffect, useState } from "react";
import { Inbox, Shield } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { FilterableTable } from "@/components/shared/FilterableTable";
import { StatusPill } from "@/components/shared/StatusPill";

type ReviewItem = { id: string; clientId: string | null; kind: string; subjectType: string; subjectId: string; status: string; reviewedBy: string | null; reviewedAt: string | null; payload: unknown; createdAt: string };
async function json<T>(response: Response): Promise<T> { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? `Request failed (${response.status})`); return body as T; }
const fetchKinds = () => fetch("/api/review-items/kinds").then(json<string[]>);
const fetchItems = (kind: string, status: string) => { const params = new URLSearchParams(); if (kind) params.set("kind", kind); if (status) params.set("status", status); return fetch(`/api/review-items${params.size ? `?${params}` : ""}`).then(json<ReviewItem[]>); };
const decide = (id: string, decision: "accept" | "reject", note: string) => fetch(`/api/review-items/${encodeURIComponent(id)}/${decision}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ note }) }).then(json<ReviewItem>);
const label = (value: string) => value.replaceAll("_", " ");
export function ReviewInboxPage() {
  const [kinds, setKinds] = useState<string[]>([]);
  const [kind, setKind] = useState("");
  const [status, setStatus] = useState("pending");
  const [rows, setRows] = useState<ReviewItem[]>([]);
  const [selected, setSelected] = useState<ReviewItem | null>(null);
  const [note, setNote] = useState("");
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { fetchKinds().then(setKinds).catch(err => setError(err.message)); }, []);
  useEffect(() => { let active = true; setLoading(true); fetchItems(kind, status).then(items => { if (active) { setRows(items); setError(""); } }).catch(err => { if (active) setError(err.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [kind, status]);
  const act = async (decision: "accept" | "reject") => { if (!selected) return; setBusy(true); try { const updated = await decide(selected.id, decision, note.trim()); setRows(current => status === "pending" ? current.filter(row => row.id !== updated.id) : current.map(row => row.id === updated.id ? updated : row)); toast.success(`Review ${decision === "accept" ? "accepted" : "rejected"}.`); setSelected(null); setNote(""); } catch (err) { toast.error(err instanceof Error ? err.message : "Unable to update review."); } finally { setBusy(false); } };
  return <section className="admin-page admin-live-page"><header className="page-heading admin-heading"><div><div className="eyebrow"><Shield size={13} /> TECHNICAL / REVIEW</div><h1>Review Inbox</h1><p>Review incoming items and record a decision.</p></div></header><div className="panel admin-table"><div className="admin-section-title"><div><Inbox size={18} /><h2>Items to review</h2></div><span>{rows.length} {status || "total"}</span></div>{kinds.length > 0 && <div className="admin-tabs" role="tablist" aria-label="Review kind"><button role="tab" aria-selected={!kind} className={!kind ? "active" : ""} onClick={() => setKind("")}>All kinds</button>{kinds.map(value => <button key={value} role="tab" aria-selected={kind === value} className={kind === value ? "active" : ""} onClick={() => setKind(value)}>{label(value)}</button>)}</div>}<div className="admin-tabs admin-tabs-subtle" role="tablist" aria-label="Review status">{[["pending", "Pending"], ["accepted", "Accepted"], ["rejected", "Rejected"]].map(([value, name]) => <button key={value} role="tab" aria-selected={status === value} className={status === value ? "active" : ""} onClick={() => setStatus(value)}>{name}</button>)}</div>{error && <p className="admin-api-error" role="alert">{error}</p>}{!loading && !error && !rows.length ? <div className="admin-review-empty"><div><Inbox size={27} /></div><h3>{status === "pending" ? "Nothing to review yet" : `No ${status} items`}</h3><p>{status === "pending" ? "New review items will appear here when connected workflows submit them." : "Items with this decision will appear here."}</p></div> : <FilterableTable rows={rows} getRowId={row => row.id} emptyMessage="Loading review items…" columns={[{ key: "kind", header: "Kind", render: row => <span className="admin-role">{label(row.kind)}</span> }, { key: "subject", header: "Subject", render: row => <strong className="admin-primary-cell">{row.subjectType} · {row.subjectId}</strong> }, { key: "created", header: "Received", render: row => new Date(row.createdAt).toLocaleString() }, { key: "status", header: "Status", render: row => <StatusPill status={row.status} /> }, { key: "action", header: "", render: row => <button className="admin-link" onClick={() => { setSelected(row); setNote(""); }}>View item</button> }]} />}</div>
    <Dialog open={!!selected} onOpenChange={next => { if (!next) setSelected(null); }}><DialogContent className="admin-dialog"><DialogTitle>{selected?.kind && label(selected.kind)}</DialogTitle><DialogDescription>{selected?.subjectType} · {selected?.subjectId}</DialogDescription><div className="admin-detail-grid"><span>Status</span><strong>{selected?.status}</strong><span>Received</span><strong>{selected && new Date(selected.createdAt).toLocaleString()}</strong></div><h3>Submitted data</h3><div className="admin-payload">{selected?.payload && typeof selected.payload === "object" && !Array.isArray(selected.payload) ? Object.entries(selected.payload).map(([key, value]) => <p key={key}><span>{label(key)}</span><strong>{typeof value === "object" ? JSON.stringify(value, null, 2) : String(value ?? "—")}</strong></p>) : <pre>{JSON.stringify(selected?.payload ?? null, null, 2)}</pre>}</div>{selected?.status === "pending" && <div className="admin-live-form"><label>Decision note (optional)<textarea rows={3} value={note} onChange={event => setNote(event.target.value)} /></label><div className="modal-actions"><button className="secondary-button" disabled={busy} onClick={() => act("reject")}>Reject</button><button className="primary-button" disabled={busy} onClick={() => act("accept")}>Accept</button></div></div>}</DialogContent></Dialog>
  </section>;
}
